In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('data1.csv')
# X: independent variable matrix & y: dependent variable vector
X = dataset.iloc[:,1:7].values
# X = pd.DataFrame(X)
Y  = dataset.iloc[:,0].values

In [3]:
from sklearn.cross_validation import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

/home/deepanshu/anaconda3/lib/python3.5/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [4]:
import keras 
from keras.models import Sequential
from keras.layers import Dense 

Using TensorFlow backend.


In [25]:
# Initializing the ANN
model = Sequential()

# Adding the input layer and the first hidden layer
model.add(Dense(4, kernel_initializer = 'uniform' , activation = 'relu', input_dim = 6))    

# Adding another hidden layer 
model.add(Dense(4, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer 
model.add(Dense(units= 1, kernel_initializer = 'uniform', activation = 'linear'))        

# Compiling the ANN
model.compile(optimizer = 'rmsprop', loss = 'mse', metrics = ['accuracy'])

In [29]:
# Fitting the ANN to the training set 
model.fit(X_train, Y_train, batch_size=8, epochs = 100)

Epoch 1/100
12/12 [==============================] - 0s 1ms/step - loss: 923.0149 - acc: 0.0000e+00
Epoch 2/100
12/12 [==============================] - 0s 982us/step - loss: 921.3420 - acc: 0.0000e+00
Epoch 3/100
12/12 [==============================] - 0s 1ms/step - loss: 922.2225 - acc: 0.0000e+00
Epoch 4/100
12/12 [==============================] - 0s 1ms/step - loss: 920.0695 - acc: 0.0000e+00
Epoch 5/100
12/12 [==============================] - 0s 991us/step - loss: 919.4494 - acc: 0.0000e+00
Epoch 6/100
12/12 [==============================] - 0s 1ms/step - loss: 919.4034 - acc: 0.0000e+00
Epoch 7/100
12/12 [==============================] - 0s 2ms/step - loss: 919.9919 - acc: 0.0000e+00
Epoch 8/100
12/12 [==============================] - 0s 1ms/step - loss: 922.2407 - acc: 0.0000e+00
Epoch 9/100
12/12 [==============================] - 0s 1ms/step - loss: 916.7600 - acc: 0.0000e+00
Epoch 10/100
12/12 [==============================] - 0s 1ms/step - loss: 921.7004 - acc: 0.0000

12/12 [==============================] - 0s 2ms/step - loss: 846.4175 - acc: 0.0000e+00
Epoch 83/100
12/12 [==============================] - 0s 2ms/step - loss: 840.4141 - acc: 0.0000e+00
Epoch 84/100
12/12 [==============================] - 0s 1ms/step - loss: 838.2360 - acc: 0.0000e+00
Epoch 85/100
12/12 [==============================] - 0s 1ms/step - loss: 842.2788 - acc: 0.0000e+00
Epoch 86/100
12/12 [==============================] - 0s 2ms/step - loss: 835.9451 - acc: 0.0000e+00
Epoch 87/100
12/12 [==============================] - 0s 1ms/step - loss: 833.9524 - acc: 0.0000e+00
Epoch 88/100
12/12 [==============================] - 0s 1ms/step - loss: 836.4393 - acc: 0.0000e+00
Epoch 89/100
12/12 [==============================] - 0s 2ms/step - loss: 832.4112 - acc: 0.0000e+00
Epoch 90/100
12/12 [==============================] - 0s 2ms/step - loss: 838.0189 - acc: 0.0000e+00
Epoch 91/100
12/12 [==============================] - 0s 1ms/step - loss: 831.9457 - acc: 0.0000e+00
Epo

In [30]:
# predicting the test set result 
Y_pred = model.predict(X_test)

In [31]:
Y_pred

array([[ 12.74158573],
       [ 26.87109375],
       [ 10.80540657],
       [  6.37382221]], dtype=float32)

In [12]:
Y_test

array([ 12.,   5.,  41.,   4.])

In [32]:
from sklearn.ensemble import ExtraTreesRegressor

In [33]:
tree = ExtraTreesRegressor()

In [34]:
tree.fit(X, Y)

ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=10, n_jobs=1, oob_score=False, random_state=None,
          verbose=0, warm_start=False)

In [35]:
print(tree.feature_importances_)

[ 0.2418477   0.08489732  0.10329783  0.20268278  0.07979714  0.28747723]


In [69]:
dataset.iloc[:,1:7]

overall_rating  positive  negative  no_of_reviews  discount_value  \
0              4.5      89.0       6.0         4949.0           124.0   
1              4.7      92.0       4.0          846.0           100.0   
2              4.1      74.0      14.0         1462.0            81.0   
3              4.3      83.0      12.0         1154.0           220.0   
4              4.2      80.0       9.0          510.0            11.0   
5              4.5      90.0       6.0         3552.0           166.0   
6              4.6      91.0       5.0         3581.0            80.0   
7              4.4      86.0       6.0          356.0           121.0   
8              3.4      52.0      31.0          226.0           155.0   
9              4.7      97.0       5.0           32.0            50.0   
10             4.2      79.0      18.0          126.0           141.0   
11             4.6      92.0       4.0          742.0            81.0   
12             4.5      90.0       5.0         2908.0            56.0   
13             4.7      93.0       4.0         1243.0           125.0   
14             4.5      90.0       4.0          529.0            68.0   
15             4.6      91.0       5.0         2127.0           145.0   

    discount_rate  
0            62.0  
1            40.0  
2            41.0  
3            44.0  
4            37.0  
5            42.0  
6            53.0  
7            48.0  
8            48.0  
9            14.0  
10           40.0  
11           41.0  
12           28.0  
13           42.0  
14           34.0  
15           37.0