In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from keras.layers.core import Dropout

Using TensorFlow backend.


In [2]:
dataset = pd.read_csv('data2.csv')
# X: independent variable matrix & y: dependent variable vector
X = dataset.iloc[:,1:7].values
# X = pd.DataFrame(X)
Y  = dataset.iloc[:,0].values

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86 entries, 0 to 85
Data columns (total 7 columns):
sales_rank        86 non-null int64
overall_rating    86 non-null float64
positive          86 non-null int64
negative          86 non-null int64
no_of_reviews     86 non-null int64
discount_value    86 non-null float64
discount_rate     86 non-null int64
dtypes: float64(2), int64(5)
memory usage: 4.8 KB


In [4]:
from sklearn.cross_validation import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

/home/deepanshu/anaconda3/lib/python3.5/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [5]:
import keras 
from keras.models import Sequential
from keras.layers import Dense 

In [10]:
# Initializing the ANN
model = Sequential()

# Adding the input layer and the first hidden layer
model.add(Dense(4, kernel_initializer = 'normal' , activation = 'relu', input_dim = 6))    

model.add(Dropout(0.1))

# Adding another hidden layer 
model.add(Dense(1, kernel_initializer = 'normal', activation = 'linear'))       
# Compiling the ANN
model.compile(optimizer = 'rmsprop', loss = 'mse', metrics = ['accuracy'])

In [11]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 4)                 28        
_________________________________________________________________
dropout_2 (Dropout)          (None, 4)                 0         
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 5         
Total params: 33
Trainable params: 33
Non-trainable params: 0
_________________________________________________________________


In [12]:
# Fitting the ANN to the training set 

model.fit(X_train, Y_train, batch_size=12, validation_split=0.1, epochs = 100)

ValueError: ('Some keys in session_kwargs are not supported at this time: %s', dict_keys(['activation']))

In [27]:
X_train[0]


array([   4.8,  100. ,    3. ,   32. ,   91. ,   36. ])

In [19]:
Y_train[0]

775

In [44]:
# predicting the test set result 
Y_pred = model.predict([   4.8,  100. ,    3. ,   32. ,   91. ,   36. ])

ValueError: Error when checking input: expected dense_6_input to have shape (6,) but got array with shape (1,)

In [37]:
Y_pred

array([[ 179.96009827],
       [ 187.06034851],
       [ 120.73935699],
       [ 200.14970398],
       [ 140.02708435],
       [ 243.04382324],
       [ 164.25111389],
       [ 166.67155457],
       [ 128.87834167],
       [ 100.45922852],
       [ 100.2610321 ],
       [ 119.81826019],
       [ 102.69457245],
       [ 140.69604492],
       [ 132.84274292],
       [  24.7064991 ],
       [  29.16340637],
       [  22.98957443],
       [ 228.18707275],
       [ 180.80192566],
       [ 100.91379547],
       [  19.1750679 ],
       [  42.05557251],
       [ 113.59910583],
       [ 302.31939697],
       [ 165.60359192],
       [  31.89430428],
       [ 503.61523438],
       [  36.1923027 ],
       [  17.77904701],
       [ 185.27053833],
       [ 201.4780426 ],
       [  46.47024155],
       [  93.1097641 ],
       [  55.92365646],
       [  58.35858536],
       [ 187.60031128],
       [ 275.92382812],
       [ 229.98228455],
       [ 149.91337585],
       [  29.68195343],
       [ 112.125

In [38]:
Y_train

array([775, 277,  64,   2, 275,  59, 215, 153, 245,  51, 628,  11, 438,
       397,  95,  16, 198,  69,  55, 148, 272,   4,  72,  78,  56,  86,
        15, 672,   7,   1, 110,  23,  17,  73,  27, 128, 369, 524,  88,
       104,   3, 126,  46,  37, 293,  98,  50, 329, 607, 394, 302, 363,
        47,  68, 276,  41,  62,  52, 151,  44, 684,  76,  53, 138, 261,
       105, 201,  19])

In [17]:
errors = abs(Y_pred - Y_test)

print('Average absolute error:', round(np.mean(errors), 2), 'degrees.')

# Calculate mean absolute percentage error (MAPE)
mape = 100 * (errors / Y_test)

# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')

Average absolute error: 190.7 degrees.
Accuracy: -329.83 %.


In [13]:
from sklearn.model_selection import KFold

In [12]:
from sklearn.ensemble import ExtraTreesRegressor

In [13]:
tree = ExtraTreesRegressor()

In [14]:
tree.fit(X, Y)

ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=10, n_jobs=1, oob_score=False, random_state=None,
          verbose=0, warm_start=False)

In [83]:
print(tree.feature_importances_)

NameError: name 'tree' is not defined

In [16]:
names = list(dataset.columns[1:])

In [17]:
imp = list(tree.feature_importances_)

In [18]:
featureImportance = list(zip(names, imp))

In [19]:
importances = list(zip(tree.feature_importances_, names))

In [47]:
importances

[(0.14751907421500249, 'overall_rating'),
 (0.18234953668276441, 'positive'),
 (0.12028841597319342, 'negative'),
 (0.22772865570612227, 'no_of_reviews'),
 (0.12581424841348957, 'discount_value'),
 (0.19630006900942795, 'discount_rate')]